apiVersion: v1
# 副本控制器RC
kind: ReplicationController
metadata:
# RC的名称(全局唯一)
  name: mysql-rc
# 标签
  labels:
    name: mysql-rc
spec:
# 副本期待数量
  replicas: 1
  selector:
# 符合目标的Pod拥有此标签
    name: mysql-pod
# 根据此模板创建Pod的实例
  template:
    metadata:
      labels:
# Pod副本拥有的标签，对应RC的Selector
        name: mysql-pod
    spec:
# 容器定义部分
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
# 容器暴露的端口
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "dmt.123"