version: '2.2'
services:
  #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  es4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es4
    environment:
      - node.name=es4
      - cluster.name=es-cluster
      - discovery.seed_hosts=es5,es6
      - node.max_local_storage_nodes=256
      - node.data=true
      - cluster.initial_master_nodes=es4,es5,es6
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - cluster.join.timeout=180s
      - cluster.publish.timeout=180s
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/workspace/docker/elasticsearch/node4/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es5:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es5
    environment:
      - node.name=es5
      - cluster.name=es-cluster
      - discovery.seed_hosts=es4,es6
      - node.max_local_storage_nodes=256
      - node.data=true
      - cluster.initial_master_nodes=es4,es5,es6
      - bootstrap.memory_lock=true
      - cluster.join.timeout=180s
      - cluster.publish.timeout=180s
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/workspace/docker/elasticsearch/node5/data:/usr/share/elasticsearch/data
    networks:
      - elastic
  es6:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es6
    environment:
      - node.name=es6
      - cluster.name=es-cluster
      - discovery.seed_hosts=es4,es5
      - node.max_local_storage_nodes=256
      - node.data=true
      - cluster.initial_master_nodes=es4,es5,es6
      - bootstrap.memory_lock=true
      - cluster.join.timeout=180s
      - cluster.publish.timeout=180s
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/workspace/docker/elasticsearch/node6/data:/usr/share/elasticsearch/data
    networks:
      - elastic
  elasticsearch-kibana:
    image: kibana:7.5.2
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es4:9200
      ELASTICSEARCH_URL: http://es4:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24

#ik分词安装
#1. docker exec -it es01 /bin/bash
#2. ./bin/elasticsearch-plugin install http://microservice.microfoolish.com/download/elasticsearch-analysis-ik-7.5.1.zip
#   ./bin/elasticsearch-plugin install http://192.168.0.101/download/elasticsearch-analysis-ik-7.5.1.zip