version: '2'
services:
  zoo1:
    image: zookeeper
    restart: always
    container_name: zoo1
    ports:
      - "2181:2181"
    volumes:
      - /Users/apaye/workspace/docker/zookeeper/zoo1/data:/data
      - /Users/apaye/workspace/docker/zookeeper/zoo1/logs:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - zoo
  zoo2:
    image: zookeeper
    restart: always
    container_name: zoo2
    ports:
      - "2182:2181"
    volumes:
      - /Users/apaye/workspace/docker/zookeeper/zoo2/data:/data
      - /Users/apaye/workspace/docker/zookeeper/zoo2/logs:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - zoo
  zoo3:
    image: zookeeper
    restart: always
    container_name: zoo3
    ports:
      - "2183:2181"
    volumes:
      - /Users/apaye/workspace/docker/zookeeper/zoo3/data:/data
      - /Users/apaye/workspace/docker/zookeeper/zoo3/logs:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - zoo
networks:
  zoo:
    driver: bridge