version: '3.6'
services:
  consul1:
    image: consul:latest
    container_name: consul1
    restart: always
    network_mode: consul-net
    command: agent -server -client=0.0.0.0 -bootstrap-expect=3 -node=consul1 -datacenter=dc1 -config-dir=/home/acl.json
    volumes:
      - ~/workspace/docker/consul/datacenter1/consul1/conf/acl.json:/home/acl.json
      - ~/workspace/docker/consul/datacenter1/consul1/data:/consul/data
  consul2:
    image: consul:latest
    container_name: consul2
    network_mode: consul-net
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul1 -node=consul2 -datacenter=dc1 -config-dir=/home/acl.json
    volumes:
      - ~/workspace/docker/consul/datacenter1/consul2/conf/acl.json:/home/acl.json
      - ~/workspace/docker/consul/datacenter1/consul2/data:/consul/data
  consul3:
    image: consul:latest
    container_name: consul3
    network_mode: consul-net
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul1 -node=consul3 -datacenter=dc1 -config-dir=/home/acl.json
    volumes:
      - ~/workspace/docker/consul/datacenter1/consul3/conf/acl.json:/home/acl.json
      - ~/workspace/docker/consul/datacenter1/consul3/data:/consul/data
  consul4:
    image: consul:latest
    container_name: consul4
    network_mode: consul-net
    restart: always
    ports:
      - 18500:8500
    command: agent -client=0.0.0.0 -retry-join=consul1 -ui -node=client1 -datacenter=dc1 -config-dir=/home/acl_client.json
    volumes:
      - ~/workspace/docker/consul/datacenter1/client1/conf/acl_client.json:/home/acl_client.json
      - ~/workspace/docker/consul/datacenter1/client1/data:/consul/data
