version: '3'
services:
  canal-server:
    image: canal/canal-server:v1.1.4
    container_name: canal-server
    restart: unless-stopped
    network_mode: host
    ports:
      - 11111:11111
    environment:
      - canal.auto.scan=false
      - canal.instance.master.address=127.0.0.1:43306
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=EWDRXbsG%pmce!EC
      - canal.instance.filter.regex=.*\\..*
      - canal.destinations=test
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
    volumes:
      - ~/workspace/docker/canal/example/conf/:/home/admin/canal-server/conf/
      - ~/workspace/docker/canal/example/logs/:/home/admin/canal-server/logs/